### ISSUE TITLE
AttributeError: type object 'DebugMsg' has no attribute 'SimulationError'

### ISSUE THREAD

**Issue by grodtron** [pfpsim/pfpdb#4]
When the debugger receives a `GenericAcknowledge` message, the following error is thrown. This can be seen in the unit tests introduced in ec6ff957e125b173b25fa2844962687d70ceca95. See [travis build 20](https://travis-ci.org/pfpsim/pfpdb/builds/134806985).

```
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/build/pfpsim/pfpdb/pfpdb/tests.py", line 99, in check_run
    debugger_cli.do_run(run_command)
  File "/home/travis/build/pfpsim/pfpdb/pfpdb/pfpdb.py", line 582, in func_wrapper
    return func(self, line)
  File "/home/travis/build/pfpsim/pfpdb/pfpdb/pfpdb.py", line 626, in do_run
    self.handleRunOrContinueReply(msg_type, reply)
  File "/home/travis/build/pfpsim/pfpdb/pfpdb/pfpdb.py", line 1514, in handleRunOrContinueReply
    elif msg_type == PFPSimDebugger_pb2.DebugMsg.SimulationError:
AttributeError: type object 'DebugMsg' has no attribute 'SimulationError'
```

Additionally this makes me think that `GenericAckowledge` is never used and should possibly be removed.
